###### curl samples (application deployed at application context `lunch-manager`).
###    > For windows use `Git Bash`
########################################################################################################################
### Profile resources
########################################################################################################################

### test UTF
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/profile/text" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/profile/text
Authorization: Basic user@yandex.ru password

### get User
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/profile" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/profile
Authorization: Basic user@yandex.ru password

### update User
# curl -X PUT --location "http://localhost:8080/lunch-manager/rest/profile"
#    -H "Content-Type: application/json"
#    -d "{
#          \"name\": \"UpdatedName\",
#          \"email\": \"user3@mail.ru\",
#          \"password\": \"newPass\",
#          \"enabled\": true,
#          \"registered\": \"2021-11-02T21:45:00\",
#          \"roles\": [
#            \"ADMIN\"
#          ]
#        }"
#    --user user@yandex.ru:password
PUT http://localhost:8080/lunch-manager/rest/profile
Authorization: Basic user@yandex.ru password
Content-Type: application/json

{
  "name": "UpdatedName",
  "email": "user3@mail.ru",
  "password": "newPass",
  "enabled": true,
  "registered": "2021-11-02T21:45:00",
  "roles": [
    "ADMIN"
  ]
}

### delete User
# curl -X DELETE --location "http://localhost:8080/lunch-manager/rest/profile" --user user@yandex.ru:password
DELETE http://localhost:8080/lunch-manager/rest/profile
Authorization: Basic user@yandex.ru password

### register User
# curl -X POST --location "http://localhost:8080/lunch-manager/rest/profile"
#    -H "Content-Type: application/json"
#    -d "{
#          \"name\": \"NewUser\",
#          \"email\": \"test@mail.ru\",
#          \"password\": \"test-password\",
#          \"enabled\": true,
#          \"registered\": \"2021-12-30T09:16:00\",
#          \"roles\": [
#            \"USER\"
#          ]
#        }"

POST http://localhost:8080/lunch-manager/rest/profile
Authorization: Basic user@yandex.ru password
Content-Type: application/json

{
  "name": "NewUser",
  "email": "test@mail.ru",
  "password": "test-password",
  "enabled": true,
  "registered": "2021-12-30T09:16:00",
  "roles": [
    "USER"
  ]
}

########################################################################################################################
###### Restaurant resources
########################################################################################################################

### get Restaurant:100004
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/restaurants/100004" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/restaurants/100004
Authorization: Basic user@yandex.ru password

### get All Restaurants
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/restaurants" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/restaurants
Authorization: Basic user@yandex.ru password

### get Restaurant:100004 with Dishes
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/restaurants/100004/with-dishes" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/restaurants/100004/with-dishes
Authorization: Basic user@yandex.ru password

########################################################################################################################
######### Dish resources
########################################################################################################################

### get Dish:100009
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/restaurants/100004/dishes/100009" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/restaurants/100004/dishes/100009
Authorization: Basic user@yandex.ru password

### get All Dishes
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/restaurants/100004/dishes" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/restaurants/100004/dishes
Authorization: Basic user@yandex.ru password

########################################################################################################################
############ Vote resources
########################################################################################################################

### create Vote
# curl -X POST --location "http://localhost:8080/lunch-manager/rest/restaurants/100004/votes"
#    -H "Content-Type: application/json"
#    -d "{
#          \"registered\": \"2021-11-06\"
#        }"
#    --user user@yandex.ru:password
POST http://localhost:8080/lunch-manager/rest/restaurants/100004/votes
Authorization: Basic user@yandex.ru password
Content-Type: application/json

{
  "registered": "2021-11-06"
}

### delete Vote:100020
# curl -X DELETE --location "http://localhost:8080/lunch-manager/rest/restaurants/100004/votes/100020 --user user@yandex.ru:password"
DELETE http://localhost:8080/lunch-manager/rest/restaurants/100004/votes/100020
Authorization: Basic user@yandex.ru password

### update Vote:100016
# curl -X PUT --location "http://localhost:8080/lunch-manager/rest/restaurants/100004/votes/100016"
#    -H "Content-Type: application/json"
#    -d "{
#          \"registered\": \"2021-10-06\"
#        }"
#    --user user@yandex.ru:password
PUT http://localhost:8080/lunch-manager/rest/restaurants/100004/votes/100016
Authorization: Basic user@yandex.ru password
Content-Type: application/json

{
  "registered": "2021-10-06"
}

### get Vote:100017
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/restaurants/100004/votes/100017" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/restaurants/100004/votes/100017
Authorization: Basic user@yandex.ru password

### get All Votes
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/restaurants/100004/votes" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/restaurants/100004/votes
Authorization: Basic user@yandex.ru password

### get Votes Between:2021-11-11&2021-11-11
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/restaurants/100004/votes/filter?startDate=2021-11-11&endDate=2021-11-11" --user user@yandex.ru:password
GET http://localhost:8080/lunch-manager/rest/restaurants/100004/votes/filter?startDate=2021-11-11&endDate=2021-11-11
Authorization: Basic user@yandex.ru password

########################################################################################################################
### Admin resources
########################################################################################################################

### create User
# curl -X POST --location "http://localhost:8080/lunch-manager/rest/admin/users"
#    -H "Content-Type: application/json"
#    -d "{
#          \"name\": \"CreatedUser\",
#          \"email\": \"user4@mail.ru\",
#          \"password\": \"123456\",
#          \"enabled\": false,
#          \"registered\": \"2021-11-02T21:45:00\",
#          \"roles\": [
#            \"USER\"
#          ]
#        }"
#    --user admin@gmail.com:admin
POST http://localhost:8080/lunch-manager/rest/admin/users
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "CreatedUser",
  "email": "user4@mail.ru",
  "password": "123456",
  "enabled": false,
  "registered": "2021-11-02T21:45:00",
  "roles": [
    "USER"
  ]
}

### delete User:100019
# curl -X DELETE --location "http://localhost:8080/lunch-manager/rest/admin/users/100019" --user admin@gmail.com:admin
DELETE http://localhost:8080/lunch-manager/rest/admin/users/100019
Authorization: Basic admin@gmail.com admin

### update User:100001
# curl -X PUT --location "http://localhost:8080/lunch-manager/rest/admin/users/100001"
#    -H "Content-Type: application/json"
#    -d "{
#          \"name\": \"UpdatedUser\",
#          \"email\": \"user1@yandex.ru\",
#          \"password\": \"newPass\",
#          \"enabled\": true,
#          \"registered\": \"2021-11-02T21:45:00\",
#          \"roles\": [
#            \"ADMIN\"
#          ]
#        }"
#    --user admin@gmail.com:admin
PUT http://localhost:8080/lunch-manager/rest/admin/users/100001
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "UpdatedUser",
  "email": "user1@yandex.ru",
  "password": "newPass",
  "enabled": true,
  "registered": "2021-11-02T21:45:00",
  "roles": [
    "ADMIN"
  ]
}

### get User:user1@yandex.ru
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/admin/users/by?email=user1@yandex.ru" --user admin@gmail.com:admin
GET http://localhost:8080/lunch-manager/rest/admin/users/by?email=user1@yandex.ru
Authorization: Basic admin@gmail.com admin

### get User:100001
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/admin/users/100001" --user admin@gmail.com:admin
GET http://localhost:8080/lunch-manager/rest/admin/users/100001
Authorization: Basic admin@gmail.com admin

### get All Users
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/admin/users" --user admin@gmail.com:admin
GET http://localhost:8080/lunch-manager/rest/admin/users
Authorization: Basic admin@gmail.com admin

### validate with Error
# curl -X POST --location "http://localhost:8080/lunch-manager/rest/admin/users"
#    -H "Content-Type: application/json"
#    -d "{}"
#    --user admin@gmail.com:admin
POST http://localhost:8080/lunch-manager/rest/admin/users
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{}

########################################################################################################################
###### Restaurant resources
########################################################################################################################

### create Restaurant
# curl -X POST --location "http://localhost:8080/lunch-manager/rest/admin/restaurants"
#    -H "Content-Type: application/json"
#    -d "{
#          \"name\": \"CreatedRestaurant\",
#          \"dishes\": null
#        }"
#    --user admin@gmail.com:admin
POST http://localhost:8080/lunch-manager/rest/admin/restaurants
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "CreatedRestaurant",
  "dishes": null
}

### delete Restaurant:100006
# curl -X DELETE --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100006" --user admin@gmail.com:admin
DELETE http://localhost:8080/lunch-manager/rest/admin/restaurants/100006
Authorization: Basic admin@gmail.com admin

### update Restaurant:100005
# curl -X PUT --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100005"
#    -H "Content-Type: application/json"
#    -d "{
#          \"name\": \"UpdatedRestaurant\",
#          \"dishes\": null
#        }"
#    --user admin@gmail.com:admin
PUT http://localhost:8080/lunch-manager/rest/admin/restaurants/100005
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "UpdatedRestaurant",
  "dishes": null
}

### get Restaurant:100004
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100004" --user admin@gmail.com:admin
GET http://localhost:8080/lunch-manager/rest/admin/restaurants/100004
Authorization: Basic admin@gmail.com admin

### get All Restaurants
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/admin/restaurants" --user admin@gmail.com:admin
GET http://localhost:8080/lunch-manager/rest/admin/restaurants
Authorization: Basic admin@gmail.com admin

### get Restaurant:100004 with dishes
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/with-dishes" --user admin@gmail.com:admin
GET http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/with-dishes
Authorization: Basic admin@gmail.com admin

########################################################################################################################
######### Dish resources
########################################################################################################################

### create Dish
# curl -X POST --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes"
#    -H "Content-Type: application/json"
#    -d "{
#          \"name\": \"CreatedDish\",
#          \"price\": 111,
#          \"registered\": \"2021-11-27\"
#        }"
#    --user admin@gmail.com:admin
POST http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "CreatedDish",
  "price": 111,
  "registered": "2021-11-27"
}

### delete Dish:100019
# curl -X DELETE --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes/100019" --user admin@gmail.com:admin
DELETE http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes/100019
Authorization: Basic admin@gmail.com admin

### update Dish:100009
# curl -X PUT --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes/100009"
#    -H "Content-Type: application/json"
#    -d "{
#          \"name\": \"UpdatedDish\",
#          \"price\": 1000,
#          \"registered\": \"2021-11-13\"
#        }"
#    --user admin@gmail.com:admin
PUT http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes/100009
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "UpdatedDish",
  "price": 1000,
  "registered": "2021-11-13"
}

### get Dish:100009
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes/100009" --user admin@gmail.com:admin
GET http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes/100009
Authorization: Basic admin@gmail.com admin

### get All Dishes
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes" --user admin@gmail.com:admin
GET http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes
Authorization: Basic admin@gmail.com admin

### get Dishes Between:2021-11-27&2021-11-27
# curl -X GET --location "http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes/filter?startDate=2021-11-27&endDate=2021-11-27" --user admin@gmail.com:admin
GET http://localhost:8080/lunch-manager/rest/admin/restaurants/100004/dishes/filter?startDate=2021-11-27&endDate=2021-11-27
Authorization: Basic admin@gmail.com admin

########################################################################################################################
